### ISSUE TITLE
Grammar with semantic predicates produces parser that won't compile

### ISSUE THREAD

**Issue by artyom-razinov** [janyou/Antlr-Swift-Runtime#3]
Steps to reproduce:
1. Get ANTLRv4 grammars: https://github.com/antlr/grammars-v4
2. Run antlr for Swift.g4: `java -cp antlr4-4.5.1.jar org.antlr.v4.Tool -Dlanguage=Swift -o gen Swift.g4`

Actutal result:
1. Swift parser has compilation errors

Expected result:
1. Swift parser can be compiled

The cause of problem is this rule for that grammar:

```
operator
  : operator_head     ({_input.get(_input.index()-1).getType()!=WS}? operator_character)*
  | dot_operator_head ({_input.get(_input.index()-1).getType()!=WS}? dot_operator_character)*
  ;
```

Swift treat "!=" as implicit unwrapping operator "!". Parser generator should replace binary operators with those that would be compiled in Swift with Antlr-Swift-Runtime.

This regex will fix issue: "([^ ])!=([^ ])" -> "$1 != $2", other binary operators can be compiled, because Swift Reference defines binary operator as operator surrounded with spaces on both sides or on neither side. I don't know why "!=" isn't tokenized as a binary operator. Maybe it's even a compiler bug.

I also don't know if it is necessary to fix this issue.

**Comment by janyou** [comment]
modify  Swift.g4:
1. **operator** ->  **theOperator**
2. **associativity** ->  **theAssociativity**
3. add whitespace before and after  operator ( **-**  /  **!=** ) 

```
theOperator
  : operator_head     ({try _input.get(_input.index() - 1).getType() != SwiftParser.WS}? operator_character)*
  | dot_operator_head ({try _input.get(_input.index() - 1).getType() != SwiftParser.WS}? dot_operator_character)*

```

[Swift.g4.zip](https://github.com/janyou/Antlr-Swift-Runtime/files/206545/Swift.g4.zip)

**Comment by artyom-razinov** [comment]
I've already made it manually. I mean, it would be cool if Swift target can work with same grammars as Java target. I also agree that it might not worth the effort.

**Comment by janyou** [comment]
**{_input.get(_input.index()-1).getType()!=WS}**  is inline code. 
Need to be changed according to different programming languages.
