### ISSUE TITLE
There are 21 cases when program would crash on try!

### ISSUE THREAD

**Issue by artyom-razinov** [janyou/Antlr-Swift-Runtime#4]
Search "try!". Every of 21 cases in this project can crash application. It is not expected behavior. There should be no unsafe "try!".

**Comment by janyou** [comment]
I hate swift's error-handling, it makes code very ugly.
 Swift need to add runtime exception feature like Java.

**Comment by artyom-razinov** [comment]
Personally I rarely use swift exceptions, only in very specific cases. I avoid them, because they aren't easy to handle (e.g.: you can not specify which exception is thrown from function). And I never use "try!", because it crashes app instantly if exception is thrown. There should be no such cases in the framework.

**Comment by artyom-razinov** [comment]
There are also lots of unsafe casts "as!" and implicit unwrapped optionals like "weak var host: SwiftParser!". They can also crash. In my projects I avoid unsafe unwrapping (as well as downcasting by the way, but downcasts are just bad architecture solutions they will not cause bugs and crashes directly)

**Comment by janyou** [comment]
What you said is right, but sometimes these are inevitable.
e.g.  unwrapped optionals implicit is useful.

```
var table: [Entry<K,V>!]
table =  [Entry<K,V>!](count: initialCapacity, repeatedValue: nil) //performance
```

Of course, these issues will be improved in the future.

**Comment by artyom-razinov** [comment]
```
var table = [Entry<K, V>]()
table.reserveCapacity(initialCapacity) // performance and safety
```

**Comment by artyom-razinov** [comment]
Also you can use

```
if let x = x {
    doSomethingWithNonnullX(x)
}
```

instead of

```
if x != nil {
    doSomethingWithNonnullX(x!)
}
```

Same for downcasts. Also you can remove downcasts by using enums with associated values.

Every downcast and every implicit unwrapping is absolutely not inevitable.

**Comment by artyom-razinov** [comment]
Runtime actually crashes on swift_unknownRelease. Seems to be an issue with unsafe pointers.

**Comment by janyou** [comment]
1.The “default values” and “reserveCapacity” are not the same.
2.I make a tool to translate Antlr Java source to Swift source.

```
if x != nil {
    doSomethingWithNonnullX(x!)
}
```

This style is easy to implement.
Basically,when the Java version run error,the swift version will run error.

**Comment by artyom-razinov** [comment]
Now I understand, thanks. Do you modify Swift code manually now, or run converter each time you want to modify code?

**Comment by janyou** [comment]
modify Swift code manually now
