### ISSUE TITLE
Sample test project  -  seems out of sync with Antlr-Swift-Target

### ISSUE THREAD

**Issue by johndpope** [janyou/Antlr-Swift-Runtime#8]
<img width="761" alt="screen shot 2016-11-06 at 15 58 48" src="https://cloud.githubusercontent.com/assets/289994/20041588/c9877fb4-a439-11e6-81f7-adcf95e959cb.png">
<img width="776" alt="screen shot 2016-11-06 at 15 58 10" src="https://cloud.githubusercontent.com/assets/289994/20041589/cd5bc6e0-a439-11e6-9e1a-1f4600f89b99.png">

the methods enterR + .r don't seem to connect.

To recreate - I have this script to spit out proto parsers.
https://gist.github.com/johndpope/ec1855edd1e51888a25a1751a2614838

maybe - this updated syntax will suffice. will try

    I want to walk the ast. If I get it working will open PR. https://github.com/SwiftTools/SwiftGrammar/blob/eb1b075b4d09d28a815fdc34768ed0c02e050141/SwiftGrammarTests/SwiftGrammarTests.swift

Parser.swif - may also be out of date.

    /**
     * The preferred method of getting a tree pattern. For example, here's a
     * sample use:
     *
     * <pre>
     * ParseTree t = parser.expr(); <- this 
     * ParseTreePattern p = parser.compileParseTreePattern("&lt;ID&gt;+0", MyParser.RULE_expr);
     * ParseTreeMatch m = p.match(t);
     * String id = m.get("ID");
     * </pre>

fyi - it's not clear how to get the parsetree.
<img width="856" alt="screen shot 2016-11-06 at 16 33 27" src="https://cloud.githubusercontent.com/assets/289994/20041909/a55c2068-a43e-11e6-881d-43bba86aacaa.png">

It's not clear where the sample Hello.g4 came from. (might be good idea to include in library)

https://github.com/search?utf8=%E2%9C%93&q=filename%3AHello.g4&type=Code&ref=searchresults

Might be good (popular + protocol buffers +  grpc + swift etc ) to replace with Proto.g4 grammar file. Ok - found the Hello grammar file - now the .r call makes sense.

<img width="832" alt="screen shot 2016-11-06 at 16 45 15" src="https://cloud.githubusercontent.com/assets/289994/20042003/62e8340e-a440-11e6-900b-b722e6f06214.png">

**Comment by johndpope** [comment]
My grammar file doesn't have a clear r /ID function to enter into 
https://raw.githubusercontent.com/vak/protobuf2uml/master/protobuf/ProtoParser.g4
any ideas? how can I get to the top level? to spit out the entire AST?

**Comment by janyou** [comment]
You'd better learn Antlr first.

`let tree = try  parser.proto()`
